# Generated by Django 3.2.25 on 2024-06-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240611_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
