# Generated by Django 3.2.25 on 2024-06-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_collection_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name_plural': 'Artists'},
        ),
    ]
