# Generated by Django 3.2.25 on 2024-06-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_artist_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='image_url',
        ),
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
